"""change diagnostics to diagnostic order

Revision ID: 03311ba29846
Revises: 56a08c35d7ad
Create Date: 2021-01-12 16:47:35.828888-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03311ba29846'
down_revision = '56a08c35d7ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
