"""removed addresses references

Revision ID: 0439b44d0905
Revises: 484b44d7c30d
Create Date: 2021-01-10 19:50:41.078264-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0439b44d0905'
down_revision = '484b44d7c30d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('addresses', 'title')
    op.drop_column('addresses', 'street_2')
    op.drop_column('addresses', 'is_business')
    op.drop_column('addresses', 'is_po_box')
    op.drop_column('addresses', 'state')
    op.drop_column('addresses', 'city')
    op.drop_column('addresses', 'zip_code')
    op.drop_column('addresses', 'street_1')
    op.drop_constraint('clinics_legal_address_id_fkey', 'clinics', type_='foreignkey')
    op.drop_column('clinics', 'legal_address_id')
    op.drop_constraint('patients_home_address_id_fkey', 'patients', type_='foreignkey')
    op.drop_constraint('patients_shipping_address_id_fkey', 'patients', type_='foreignkey')
    op.drop_column('patients', 'home_address_id')
    op.drop_column('patients', 'shipping_address_id')
    op.drop_constraint('providers_address_id_fkey', 'providers', type_='foreignkey')
    op.drop_column('providers', 'address_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('providers', sa.Column('address_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('providers_address_id_fkey', 'providers', 'addresses', ['address_id'], ['id'])
    op.add_column('patients', sa.Column('shipping_address_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('patients', sa.Column('home_address_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('patients_shipping_address_id_fkey', 'patients', 'addresses', ['shipping_address_id'], ['id'])
    op.create_foreign_key('patients_home_address_id_fkey', 'patients', 'addresses', ['home_address_id'], ['id'])
    op.add_column('clinics', sa.Column('legal_address_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('clinics_legal_address_id_fkey', 'clinics', 'addresses', ['legal_address_id'], ['id'])
    op.add_column('addresses', sa.Column('street_1', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('addresses', sa.Column('zip_code', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('addresses', sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('addresses', sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('addresses', sa.Column('is_po_box', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('addresses', sa.Column('is_business', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('addresses', sa.Column('street_2', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('addresses', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
