"""add insurer model

Revision ID: 22568c3ab198
Revises: 209a769838a5
Create Date: 2021-01-10 18:28:03.404453-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22568c3ab198'
down_revision = '209a769838a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insurer',
    sa.Column('insurer_id', sa.Integer(), nullable=False),
    sa.Column('insurer_name', sa.String(), nullable=True),
    sa.Column('edi_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('insurer_id')
    )
    op.create_index(op.f('ix_insurer_insurer_id'), 'insurer', ['insurer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_insurer_insurer_id'), table_name='insurer')
    op.drop_table('insurer')
    # ### end Alembic commands ###
