"""drop joins from clinics

Revision ID: 379eba717421
Revises: a2b641c7292f
Create Date: 2021-01-10 19:40:52.939237-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '379eba717421'
down_revision = 'a2b641c7292f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
