"""more more table updates

Revision ID: 49a89e61c4df
Revises: 50735f5d382f
Create Date: 2020-12-21 14:07:47.026987-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49a89e61c4df'
down_revision = '50735f5d382f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_address_address_id'), 'address', ['address_id'], unique=False)
    op.drop_index('ix_address_id', table_name='address')
    op.drop_column('address', 'id')
    op.create_index(op.f('ix_assay_assay_id'), 'assay', ['assay_id'], unique=False)
    op.drop_index('ix_assay_id', table_name='assay')
    op.drop_column('assay', 'id')
    op.create_index(op.f('ix_clinic_clinic_id'), 'clinic', ['clinic_id'], unique=False)
    op.drop_index('ix_clinic_id', table_name='clinic')
    op.drop_column('clinic', 'id')
    op.add_column('device', sa.Column('device_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_device_device_id'), 'device', ['device_id'], unique=False)
    op.drop_index('ix_device_id', table_name='device')
    op.drop_column('device', 'id')
    op.create_index(op.f('ix_kit_kit_id'), 'kit', ['kit_id'], unique=False)
    op.drop_index('ix_kit_id', table_name='kit')
    op.drop_column('kit', 'id')
    op.create_index(op.f('ix_lab_lab_id'), 'lab', ['lab_id'], unique=False)
    op.drop_index('ix_lab_id', table_name='lab')
    op.drop_column('lab', 'id')
    op.add_column('lab_order', sa.Column('order_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_lab_order_order_id'), 'lab_order', ['order_id'], unique=False)
    op.drop_index('ix_lab_order_id', table_name='lab_order')
    op.drop_column('lab_order', 'id')
    op.create_index(op.f('ix_patient_patient_id'), 'patient', ['patient_id'], unique=False)
    op.drop_index('ix_patient_id', table_name='patient')
    op.drop_column('patient', 'id')
    op.create_index(op.f('ix_prescription__patient_prescription_id'), 'prescription__patient', ['prescription_id'], unique=False)
    op.drop_index('ix_prescription__patient_id', table_name='prescription__patient')
    op.drop_column('prescription__patient', 'id')
    op.create_index(op.f('ix_provider_provider_id'), 'provider', ['provider_id'], unique=False)
    op.drop_index('ix_provider_id', table_name='provider')
    op.drop_column('provider', 'id')
    op.add_column('state_license', sa.Column('id', sa.Integer(), nullable=False))
    op.alter_column('state_license', 'provider_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_state_license_id'), 'state_license', ['id'], unique=False)
    op.drop_index('ix_state_license_provider_id', table_name='state_license')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_state_license_provider_id', 'state_license', ['provider_id'], unique=False)
    op.drop_index(op.f('ix_state_license_id'), table_name='state_license')
    op.alter_column('state_license', 'provider_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('state_license', 'id')
    op.add_column('provider', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.create_index('ix_provider_id', 'provider', ['id'], unique=False)
    op.drop_index(op.f('ix_provider_provider_id'), table_name='provider')
    op.add_column('prescription__patient', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.create_index('ix_prescription__patient_id', 'prescription__patient', ['id'], unique=False)
    op.drop_index(op.f('ix_prescription__patient_prescription_id'), table_name='prescription__patient')
    op.add_column('patient', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.create_index('ix_patient_id', 'patient', ['id'], unique=False)
    op.drop_index(op.f('ix_patient_patient_id'), table_name='patient')
    op.add_column('lab_order', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.create_index('ix_lab_order_id', 'lab_order', ['id'], unique=False)
    op.drop_index(op.f('ix_lab_order_order_id'), table_name='lab_order')
    op.drop_column('lab_order', 'order_id')
    op.add_column('lab', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.create_index('ix_lab_id', 'lab', ['id'], unique=False)
    op.drop_index(op.f('ix_lab_lab_id'), table_name='lab')
    op.add_column('kit', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.create_index('ix_kit_id', 'kit', ['id'], unique=False)
    op.drop_index(op.f('ix_kit_kit_id'), table_name='kit')
    op.add_column('device', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.create_index('ix_device_id', 'device', ['id'], unique=False)
    op.drop_index(op.f('ix_device_device_id'), table_name='device')
    op.drop_column('device', 'device_id')
    op.add_column('clinic', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.create_index('ix_clinic_id', 'clinic', ['id'], unique=False)
    op.drop_index(op.f('ix_clinic_clinic_id'), table_name='clinic')
    op.add_column('assay', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.create_index('ix_assay_id', 'assay', ['id'], unique=False)
    op.drop_index(op.f('ix_assay_assay_id'), table_name='assay')
    op.add_column('address', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.create_index('ix_address_id', 'address', ['id'], unique=False)
    op.drop_index(op.f('ix_address_address_id'), table_name='address')
    # ### end Alembic commands ###
