"""more table updates

Revision ID: 50735f5d382f
Revises: 7bc5d09a9e82
Create Date: 2020-12-21 13:15:51.531017-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50735f5d382f'
down_revision = '7bc5d09a9e82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('address_id', sa.Integer(), nullable=True))
    op.add_column('assay', sa.Column('assay_id', sa.Integer(), nullable=True))
    op.add_column('clinic', sa.Column('clinic_id', sa.Integer(), nullable=True))
    op.add_column('insurer', sa.Column('insurer_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_insurer_insurer_id'), 'insurer', ['insurer_id'], unique=False)
    op.drop_index('ix_insurer_id', table_name='insurer')
    op.drop_column('insurer', 'id')
    op.add_column('lab', sa.Column('lab_id', sa.Integer(), nullable=True))
    op.add_column('patient', sa.Column('patient_id', sa.Integer(), nullable=True))
    op.add_column('patient__social', sa.Column('network_id', sa.String(), nullable=True))
    op.drop_column('patient__social', 'facebook')
    op.add_column('prescription__patient', sa.Column('prescription_id', sa.Integer(), nullable=True))
    op.add_column('provider', sa.Column('provider_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('provider', 'provider_id')
    op.drop_column('prescription__patient', 'prescription_id')
    op.add_column('patient__social', sa.Column('facebook', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('patient__social', 'network_id')
    op.drop_column('patient', 'patient_id')
    op.drop_column('lab', 'lab_id')
    op.add_column('insurer', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.create_index('ix_insurer_id', 'insurer', ['id'], unique=False)
    op.drop_index(op.f('ix_insurer_insurer_id'), table_name='insurer')
    op.drop_column('insurer', 'insurer_id')
    op.drop_column('clinic', 'clinic_id')
    op.drop_column('assay', 'assay_id')
    op.drop_column('address', 'address_id')
    # ### end Alembic commands ###
