"""adding laborders back in as diagnostics

Revision ID: 56a08c35d7ad
Revises: 6e8ee22c0a5b
Create Date: 2021-01-12 16:32:36.837706-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56a08c35d7ad'
down_revision = '6e8ee22c0a5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('long_name', sa.String(), nullable=True),
    sa.Column('short_name', sa.String(), nullable=True),
    sa.Column('loinc_code', sa.String(), nullable=True),
    sa.Column('cpt_code', sa.String(), nullable=True),
    sa.Column('cash_price', sa.Float(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assays_id'), 'assays', ['id'], unique=False)
    op.create_table('kits',
    sa.Column('kit_id', sa.Integer(), nullable=False),
    sa.Column('kit_name', sa.String(), nullable=True),
    sa.Column('kit_sku', sa.String(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('shipping_speed', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('outbound_tracking', sa.String(), nullable=True),
    sa.Column('delivered_to_recepient', sa.Boolean(), nullable=True),
    sa.Column('inbound_tracking', sa.String(), nullable=True),
    sa.Column('delivered_to_lab', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('kit_id')
    )
    op.create_index(op.f('ix_kits_kit_id'), 'kits', ['kit_id'], unique=False)
    op.create_table('diagnostic_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lab_order_number', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('clinic_id', sa.Integer(), nullable=True),
    sa.Column('assay_id', sa.Integer(), nullable=True),
    sa.Column('collection_date', sa.Date(), nullable=True),
    sa.Column('replacement', sa.Boolean(), nullable=True),
    sa.Column('cash_price', sa.Float(), nullable=True),
    sa.Column('insurance_bill', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['assay_id'], ['assays.id'], ),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnostic_orders_id'), 'diagnostic_orders', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_diagnostic_orders_id'), table_name='diagnostic_orders')
    op.drop_table('diagnostic_orders')
    op.drop_index(op.f('ix_kits_kit_id'), table_name='kits')
    op.drop_table('kits')
    op.drop_index(op.f('ix_assays_id'), table_name='assays')
    op.drop_table('assays')
    # ### end Alembic commands ###
