"""updating provider model

Revision ID: 5ef2b7cd57b2
Revises: 6172d3aacef0
Create Date: 2021-01-10 18:20:24.688554-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ef2b7cd57b2'
down_revision = '6172d3aacef0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('providers', sa.Column('is_accepting_patients', sa.Boolean(), nullable=True))
    op.add_column('providers', sa.Column('is_public', sa.Boolean(), nullable=True))
    op.add_column('providers', sa.Column('mtl_provider_id', sa.String(), nullable=True))
    op.add_column('providers', sa.Column('state_license_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'providers', ['mtl_provider_id'])
    op.create_foreign_key(None, 'providers', 'state_licenses', ['state_license_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'providers', type_='foreignkey')
    op.drop_constraint(None, 'providers', type_='unique')
    op.drop_column('providers', 'state_license_id')
    op.drop_column('providers', 'mtl_provider_id')
    op.drop_column('providers', 'is_public')
    op.drop_column('providers', 'is_accepting_patients')
    # ### end Alembic commands ###
