"""first alembic revision

Revision ID: 5f997fe0a691
Revises: 
Create Date: 2021-01-23 14:22:28.575991-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f997fe0a691'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('long_name', sa.String(), nullable=True),
    sa.Column('short_name', sa.String(), nullable=True),
    sa.Column('loinc_code', sa.String(), nullable=True),
    sa.Column('cpt_code', sa.String(), nullable=True),
    sa.Column('cash_price', sa.Float(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assays_id'), 'assays', ['id'], unique=False)
    op.create_table('clinics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('legal_name', sa.String(), nullable=True),
    sa.Column('npi', sa.Integer(), nullable=True),
    sa.Column('contact_name', sa.String(), nullable=True),
    sa.Column('contact_email', sa.String(), nullable=True),
    sa.Column('contact_phone', sa.String(), nullable=True),
    sa.Column('billing_contact_name', sa.String(), nullable=True),
    sa.Column('billing_contact_email', sa.String(), nullable=True),
    sa.Column('billing_contact_phone', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('is_accepting_patients', sa.Boolean(), nullable=True),
    sa.Column('has_BAA', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinics_id'), 'clinics', ['id'], unique=False)
    op.create_table('kits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kit_name', sa.String(), nullable=True),
    sa.Column('kit_sku', sa.String(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('shipping_speed', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('outbound_tracking', sa.String(), nullable=True),
    sa.Column('delivered_to_recepient', sa.Boolean(), nullable=True),
    sa.Column('inbound_tracking', sa.String(), nullable=True),
    sa.Column('delivered_to_lab', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kits_id'), 'kits', ['id'], unique=False)
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('legal_first_name', sa.String(), nullable=True),
    sa.Column('legal_last_name', sa.String(), nullable=True),
    sa.Column('ssn', sa.Integer(), nullable=True),
    sa.Column('preferred_first_name', sa.String(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('ethnicity', sa.String(), nullable=True),
    sa.Column('race', sa.String(), nullable=True),
    sa.Column('sex_at_birth', sa.String(), nullable=True),
    sa.Column('gender_identity', sa.String(), nullable=True),
    sa.Column('religion', sa.String(), nullable=True),
    sa.Column('primary_language', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone_day', sa.String(), nullable=True),
    sa.Column('phone_night', sa.String(), nullable=True),
    sa.Column('labs_hipaa_auth', sa.Boolean(), nullable=True),
    sa.Column('labs_hipaa_auth_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_id'), 'patients', ['id'], unique=False)
    op.create_table('providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('npi', sa.Integer(), nullable=True),
    sa.Column('medicaid_id', sa.String(), nullable=True),
    sa.Column('mtl_provider_id', sa.String(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('is_accepting_patients', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('mtl_provider_id'),
    sa.UniqueConstraint('npi')
    )
    op.create_index(op.f('ix_providers_id'), 'providers', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_provider', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('diagnostic_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('diagnostic_order_number', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('clinic_id', sa.Integer(), nullable=True),
    sa.Column('assay_id', sa.Integer(), nullable=True),
    sa.Column('collection_date', sa.Date(), nullable=True),
    sa.Column('replacement', sa.Boolean(), nullable=True),
    sa.Column('cash_price', sa.Float(), nullable=True),
    sa.Column('insurance_bill', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['assay_id'], ['assays.id'], ),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnostic_orders_id'), 'diagnostic_orders', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_diagnostic_orders_id'), table_name='diagnostic_orders')
    op.drop_table('diagnostic_orders')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_providers_id'), table_name='providers')
    op.drop_table('providers')
    op.drop_index(op.f('ix_patients_id'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_kits_id'), table_name='kits')
    op.drop_table('kits')
    op.drop_index(op.f('ix_clinics_id'), table_name='clinics')
    op.drop_table('clinics')
    op.drop_index(op.f('ix_assays_id'), table_name='assays')
    op.drop_table('assays')
    # ### end Alembic commands ###
