"""updated kit model

Revision ID: 7993f215c9be
Revises: 4ca72989cd66
Create Date: 2021-01-13 06:20:36.587478-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7993f215c9be'
down_revision = '4ca72989cd66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kits', sa.Column('id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_kits_id'), 'kits', ['id'], unique=False)
    op.drop_index('ix_kits_kit_id', table_name='kits')
    op.drop_column('kits', 'kit_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kits', sa.Column('kit_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.create_index('ix_kits_kit_id', 'kits', ['kit_id'], unique=False)
    op.drop_index(op.f('ix_kits_id'), table_name='kits')
    op.drop_column('kits', 'id')
    # ### end Alembic commands ###
