"""add patient model

Revision ID: a0ebff8a1e30
Revises: 8b52f00d97ab
Create Date: 2021-01-10 18:24:15.883578-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0ebff8a1e30'
down_revision = '8b52f00d97ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('legal_first_name', sa.String(), nullable=True),
    sa.Column('legal_last_name', sa.String(), nullable=True),
    sa.Column('ssn', sa.Integer(), nullable=True),
    sa.Column('preferred_first_name', sa.String(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('ethnicity', sa.String(), nullable=True),
    sa.Column('race', sa.String(), nullable=True),
    sa.Column('sex_at_birth', sa.String(), nullable=True),
    sa.Column('gender_identity', sa.String(), nullable=True),
    sa.Column('religion', sa.String(), nullable=True),
    sa.Column('primary_language', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone_day', sa.String(), nullable=True),
    sa.Column('phone_night', sa.String(), nullable=True),
    sa.Column('labs_hipaa_auth', sa.Boolean(), nullable=True),
    sa.Column('labs_hipaa_auth_date', sa.Date(), nullable=True),
    sa.Column('shipping_address_id', sa.Integer(), nullable=True),
    sa.Column('home_address_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['home_address_id'], ['addresses.id'], ),
    sa.ForeignKeyConstraint(['shipping_address_id'], ['addresses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_id'), 'patients', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patients_id'), table_name='patients')
    op.drop_table('patients')
    # ### end Alembic commands ###
