"""changed lab order number to string

Revision ID: aad9bbed60f9
Revises: 5f997fe0a691
Create Date: 2021-01-25 13:24:45.542507-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aad9bbed60f9'
down_revision = '5f997fe0a691'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
