"""add addresses

Revision ID: b6839d156a44
Revises: e4a4cbc5f1f4
Create Date: 2021-01-10 18:19:12.705820-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6839d156a44'
down_revision = 'e4a4cbc5f1f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('state_licenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_state_licenses_id'), 'state_licenses', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_state_licenses_id'), table_name='state_licenses')
    op.drop_table('state_licenses')
    # ### end Alembic commands ###
