"""add an npi column to the clinic table

Revision ID: d422b5251dc3
Revises: 03311ba29846
Create Date: 2021-01-13 06:06:51.413911-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd422b5251dc3'
down_revision = '03311ba29846'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clinics', sa.Column('npi', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clinics', 'npi')
    # ### end Alembic commands ###
