"""drop rest of lab stuff

Revision ID: d7954848d1be
Revises: dbb48f55178c
Create Date: 2021-01-10 19:45:21.708704-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7954848d1be'
down_revision = 'dbb48f55178c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
