"""drop state licenses

Revision ID: 02af34fd963f
Revises: 25e1b3ffb283
Create Date: 2021-01-10 19:32:07.718531-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02af34fd963f'
down_revision = '25e1b3ffb283'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
