"""drop entity joins

Revision ID: 0991dd2de49d
Revises: 5cf094fc0088
Create Date: 2021-01-10 19:38:01.450738-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0991dd2de49d'
down_revision = '5cf094fc0088'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_providers_clinics_id', table_name='providers_clinics')
    op.drop_table('providers_clinics')
    op.drop_index('ix_clinics_patients_id', table_name='clinics_patients')
    op.drop_table('clinics_patients')
    op.drop_index('ix_labs_patients_id', table_name='labs_patients')
    op.drop_table('labs_patients')
    op.drop_index('ix_insurer_patient_id', table_name='insurer_patient')
    op.drop_table('insurer_patient')
    op.drop_index('ix_providers_patients_id', table_name='providers_patients')
    op.drop_table('providers_patients')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('providers_patients',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('provider_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('hipaa_auth', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('hipaa_auth_expire', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name='providers_patients_patient_id_fkey'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], name='providers_patients_provider_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='providers_patients_pkey')
    )
    op.create_index('ix_providers_patients_id', 'providers_patients', ['id'], unique=False)
    op.create_table('insurer_patient',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('member_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('group_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('pbm_bin', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('pbm_pcn', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('pbm_rx_group_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='insurer_patient_pkey')
    )
    op.create_index('ix_insurer_patient_id', 'insurer_patient', ['id'], unique=False)
    op.create_table('labs_patients',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('provider_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('clinic_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('hipaa_auth', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('hipaa_auth_expire', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], name='labs_patients_clinic_id_fkey'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], name='labs_patients_provider_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='labs_patients_pkey')
    )
    op.create_index('ix_labs_patients_id', 'labs_patients', ['id'], unique=False)
    op.create_table('clinics_patients',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('clinic_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('patient_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('hipaa_auth', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('hipaa_auth_expire', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], name='clinics_patients_clinic_id_fkey'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name='clinics_patients_patient_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='clinics_patients_pkey')
    )
    op.create_index('ix_clinics_patients_id', 'clinics_patients', ['id'], unique=False)
    op.create_table('providers_clinics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('provider_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('clinic_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], name='providers_clinics_clinic_id_fkey'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], name='providers_clinics_provider_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='providers_clinics_pkey')
    )
    op.create_index('ix_providers_clinics_id', 'providers_clinics', ['id'], unique=False)
    # ### end Alembic commands ###
