"""add kit model

Revision ID: 209a769838a5
Revises: 5257d0b55e7d
Create Date: 2021-01-10 18:26:44.492593-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '209a769838a5'
down_revision = '5257d0b55e7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kits',
    sa.Column('kit_id', sa.Integer(), nullable=False),
    sa.Column('kit_name', sa.String(), nullable=True),
    sa.Column('kit_sku', sa.String(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('shipping_speed', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('outbound_tracking', sa.String(), nullable=True),
    sa.Column('delivered_to_recepient', sa.Boolean(), nullable=True),
    sa.Column('inbound_tracking', sa.String(), nullable=True),
    sa.Column('delivered_to_processor', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('kit_id')
    )
    op.create_index(op.f('ix_kits_kit_id'), 'kits', ['kit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kits_kit_id'), table_name='kits')
    op.drop_table('kits')
    # ### end Alembic commands ###
