"""removed addresses completely

Revision ID: 33af977596df
Revises: 0439b44d0905
Create Date: 2021-01-10 19:51:01.387846-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33af977596df'
down_revision = '0439b44d0905'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_addresses_id', table_name='addresses')
    op.drop_table('addresses')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='addresses_pkey')
    )
    op.create_index('ix_addresses_id', 'addresses', ['id'], unique=False)
    # ### end Alembic commands ###
