"""drop joins from provider

Revision ID: 4d8a420c7cb1
Revises: 379eba717421
Create Date: 2021-01-10 19:41:30.965728-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d8a420c7cb1'
down_revision = '379eba717421'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
