"""drop state licenses

Revision ID: 5cf094fc0088
Revises: 02af34fd963f
Create Date: 2021-01-10 19:33:33.967508-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cf094fc0088'
down_revision = '02af34fd963f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_state_licenses_id', table_name='state_licenses')
    op.drop_table('state_licenses')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('state_licenses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='state_licenses_pkey')
    )
    op.create_index('ix_state_licenses_id', 'state_licenses', ['id'], unique=False)
    # ### end Alembic commands ###
