"""add device/assay/etc joins model

Revision ID: 6290cdd7ed1e
Revises: 22568c3ab198
Create Date: 2021-01-10 18:29:44.601805-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6290cdd7ed1e'
down_revision = '22568c3ab198'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kit_device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kit_device_id'), 'kit_device', ['id'], unique=False)
    op.create_table('orders_assays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_assays_id'), 'orders_assays', ['id'], unique=False)
    op.create_table('labs_assays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lab_id', sa.Integer(), nullable=True),
    sa.Column('assay_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assay_id'], ['assays.id'], ),
    sa.ForeignKeyConstraint(['lab_id'], ['labs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_labs_assays_id'), 'labs_assays', ['id'], unique=False)
    op.create_table('labs_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lab_order_number', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('clinic_id', sa.Integer(), nullable=True),
    sa.Column('assay_id', sa.Integer(), nullable=True),
    sa.Column('collection_date', sa.Date(), nullable=True),
    sa.Column('replacement', sa.Boolean(), nullable=True),
    sa.Column('cash_price', sa.Float(), nullable=True),
    sa.Column('insurance_bill', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['assay_id'], ['assays.id'], ),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_labs_orders_id'), 'labs_orders', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_labs_orders_id'), table_name='labs_orders')
    op.drop_table('labs_orders')
    op.drop_index(op.f('ix_labs_assays_id'), table_name='labs_assays')
    op.drop_table('labs_assays')
    op.drop_index(op.f('ix_orders_assays_id'), table_name='orders_assays')
    op.drop_table('orders_assays')
    op.drop_index(op.f('ix_kit_device_id'), table_name='kit_device')
    op.drop_table('kit_device')
    # ### end Alembic commands ###
