"""adding assay and kit models back to database

Revision ID: 6e8ee22c0a5b
Revises: 33af977596df
Create Date: 2021-01-12 16:30:16.644039-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e8ee22c0a5b'
down_revision = '33af977596df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
