"""add assay model

Revision ID: 7390a885f72a
Revises: 927f89cca2ca
Create Date: 2021-01-10 18:23:02.522321-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7390a885f72a'
down_revision = '927f89cca2ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
