"""add lab model

Revision ID: 927f89cca2ca
Revises: 4a9566e47018
Create Date: 2021-01-10 18:22:29.338780-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '927f89cca2ca'
down_revision = '4a9566e47018'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('labs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('legal_name', sa.String(), nullable=True),
    sa.Column('legal_address_id', sa.Integer(), nullable=True),
    sa.Column('contact_name', sa.String(), nullable=True),
    sa.Column('contact_email', sa.String(), nullable=True),
    sa.Column('contact_phone', sa.String(), nullable=True),
    sa.Column('billing_contact_name', sa.String(), nullable=True),
    sa.Column('billing_contact_email', sa.String(), nullable=True),
    sa.Column('billing_contact_phone', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['legal_address_id'], ['addresses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_labs_id'), 'labs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_labs_id'), table_name='labs')
    op.drop_table('labs')
    # ### end Alembic commands ###
