"""drop prescriptions/insurers

Revision ID: a2b641c7292f
Revises: 0991dd2de49d
Create Date: 2021-01-10 19:40:15.330928-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2b641c7292f'
down_revision = '0991dd2de49d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_prescriptions_id', table_name='prescriptions')
    op.drop_table('prescriptions')
    op.drop_index('ix_insurer_insurer_id', table_name='insurer')
    op.drop_table('insurer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insurer',
    sa.Column('insurer_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('insurer_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('edi_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('insurer_id', name='insurer_pkey')
    )
    op.create_index('ix_insurer_insurer_id', 'insurer', ['insurer_id'], unique=False)
    op.create_table('prescriptions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('provider_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rx_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('rx_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('rx_quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rx_strength', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('rx_expiration', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('fills_remaining', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name='prescriptions_patient_id_fkey'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], name='prescriptions_provider_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='prescriptions_pkey')
    )
    op.create_index('ix_prescriptions_id', 'prescriptions', ['id'], unique=False)
    # ### end Alembic commands ###
