"""add patient/clinic/provider joins model

Revision ID: ac57535aaa21
Revises: 6290cdd7ed1e
Create Date: 2021-01-10 18:31:43.000794-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac57535aaa21'
down_revision = '6290cdd7ed1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insurer_patient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.String(), nullable=True),
    sa.Column('group_id', sa.String(), nullable=True),
    sa.Column('pbm_bin', sa.String(), nullable=True),
    sa.Column('pbm_pcn', sa.String(), nullable=True),
    sa.Column('pbm_rx_group_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insurer_patient_id'), 'insurer_patient', ['id'], unique=False)
    op.create_table('clinics_patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('hipaa_auth', sa.Boolean(), nullable=True),
    sa.Column('hipaa_auth_expire', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinics_patients_id'), 'clinics_patients', ['id'], unique=False)
    op.create_table('labs_patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('clinic_id', sa.Integer(), nullable=True),
    sa.Column('hipaa_auth', sa.Boolean(), nullable=True),
    sa.Column('hipaa_auth_expire', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_labs_patients_id'), 'labs_patients', ['id'], unique=False)
    op.create_table('providers_clinics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('clinic_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_providers_clinics_id'), 'providers_clinics', ['id'], unique=False)
    op.create_table('providers_patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('hipaa_auth', sa.Boolean(), nullable=True),
    sa.Column('hipaa_auth_expire', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_providers_patients_id'), 'providers_patients', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_providers_patients_id'), table_name='providers_patients')
    op.drop_table('providers_patients')
    op.drop_index(op.f('ix_providers_clinics_id'), table_name='providers_clinics')
    op.drop_table('providers_clinics')
    op.drop_index(op.f('ix_labs_patients_id'), table_name='labs_patients')
    op.drop_table('labs_patients')
    op.drop_index(op.f('ix_clinics_patients_id'), table_name='clinics_patients')
    op.drop_table('clinics_patients')
    op.drop_index(op.f('ix_insurer_patient_id'), table_name='insurer_patient')
    op.drop_table('insurer_patient')
    # ### end Alembic commands ###
