"""drop lab joins

Revision ID: dbb48f55178c
Revises: 4d8a420c7cb1
Create Date: 2021-01-10 19:44:46.828552-08:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dbb48f55178c'
down_revision = '4d8a420c7cb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_orders_assays_id', table_name='orders_assays')
    op.drop_table('orders_assays')
    op.drop_index('ix_kit_device_id', table_name='kit_device')
    op.drop_table('kit_device')
    op.drop_index('ix_labs_assays_id', table_name='labs_assays')
    op.drop_table('labs_assays')
    op.drop_index('ix_labs_orders_id', table_name='labs_orders')
    op.drop_table('labs_orders')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('labs_orders',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('lab_order_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('patient_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('provider_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('clinic_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('assay_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('collection_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('replacement', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('cash_price', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('insurance_bill', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['assay_id'], ['assays.id'], name='labs_orders_assay_id_fkey'),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], name='labs_orders_clinic_id_fkey'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name='labs_orders_patient_id_fkey'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], name='labs_orders_provider_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='labs_orders_pkey')
    )
    op.create_index('ix_labs_orders_id', 'labs_orders', ['id'], unique=False)
    op.create_table('labs_assays',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('lab_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('assay_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['assay_id'], ['assays.id'], name='labs_assays_assay_id_fkey'),
    sa.ForeignKeyConstraint(['lab_id'], ['labs.id'], name='labs_assays_lab_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='labs_assays_pkey')
    )
    op.create_index('ix_labs_assays_id', 'labs_assays', ['id'], unique=False)
    op.create_table('kit_device',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='kit_device_pkey')
    )
    op.create_index('ix_kit_device_id', 'kit_device', ['id'], unique=False)
    op.create_table('orders_assays',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='orders_assays_pkey')
    )
    op.create_index('ix_orders_assays_id', 'orders_assays', ['id'], unique=False)
    # ### end Alembic commands ###
