#!/usr/bin/env python3

from collections import defaultdict
import boto3
import os.path
import subprocess
import time

DOCKER_PRUNE_CMD = "docker system prune -f"
DEFAULT_REGISTRY = "339302979805.dkr.ecr.us-east-2.amazonaws.com"
DEFAULT_AWS_REGION = "us-east-2"
DEFAULT_ENVIRONMENT = "staging"  # unused
SSM_CLIENT = boto3.client('ssm')


def git_short_rev():
    cmd = ['git', 'rev-parse', '--short', 'HEAD']
    return subprocess.check_output(cmd).decode().strip()


def get_ecr_login_cmd(region=DEFAULT_AWS_REGION, registry=DEFAULT_REGISTRY):
    get_login = f"aws ecr get-login-password --region {region}"
    docker_login = f"docker login --username AWS --password-stdin {registry}"
    return f"{get_login} | {docker_login}"


def get_docker_pull_cmd(repo, tag):
    return f"docker pull {repo}:{tag}"


def get_update_cmd(compose_fpath="/root/docker-compose.yml", **tags):
    envs = []
    services = []
    base = f"docker-compose -f {compose_fpath} up -d"

    for k, v in tags.items():
        envs.append(f"{k.upper()}_TAG={v}")
        services.append(k)

    envs = " ".join(envs)
    services = " ".join(services)

    return f"{envs} {base} {services}"


def parse_args(args, default_tag=None):
    """
    Args will come in as a list of:
    service_name[=tag]
    """
    result = {}

    for arg in args:
        parts = arg.split("=")
        if len(parts) == 1:
            service = parts[0]
            tag = default_tag or git_short_rev()
        elif len(parts) == 2:
            service, tag = parts
        else:
            raise TypeError("arguments should look like service[=tag]")

        result[service] = tag

    return result


def update(aws_region=DEFAULT_AWS_REGION, registry=DEFAULT_REGISTRY, **kwargs):
    cmds = [DOCKER_PRUNE_CMD, get_ecr_login_cmd()]
    for k, v in kwargs.items():
        repo = os.path.join(registry, f"kalamadoo-{k}")
        cmds.append(get_docker_pull_cmd(repo, v))

    logging.info("starting deployment")
    cmds.append(get_update_cmd(**kwargs))
    resp = SSM_CLIENT.send_command(
        Targets=[{
            "Key": "tag:Name",
            "Values": ["portal"]
        }],
        DocumentName="AWS-RunShellScript",
        MaxConcurrency="25%",
        Parameters={"commands": cmds},
    )

    cmd_id = resp["Command"]["CommandId"]
    logging.info("monitoring deployment")
    while True:
        time.sleep(5)
        logging.info("deploying...")

        counts = defaultdict(int)
        invocations = SSM_CLIENT.list_command_invocations(CommandId=cmd_id)
        for data in invocations['CommandInvocations']:
            counts[data['Status']] += 1

        if counts.get('Failed'):
            raise Exception('deployment failed')
        elif len(counts) == 1:
            break

    return


if __name__ == "__main__":
    import logging
    import sys

    logging.getLogger().setLevel(logging.INFO)
    try:
        rev = git_short_rev()
    except subprocess.CalledProcessError:
        msg = "Unable to get short hash of git revision, are you in the repo?"
        logging.error(msg)
        sys.exit(1)

    todo = parse_args(sys.argv[1:], default_tag=rev)
    update(**todo)
