kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: backend
  namespace: kalamadoo

spec:
  rules:
    - host: {{ .Values.backend.ingress.host }}
      http:
        paths:
          - path: /
            backend:
              serviceName: backend
              servicePort: 80

---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: frontend
  namespace: kalamadoo

spec:
  rules:
    - host: {{ .Values.frontend.ingress.host }}
      http:
        paths:
          - path: /api
            backend:
              serviceName: backend
              servicePort: 80
          - path: /
            backend:
              serviceName: frontend
              servicePort: 80
