apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: kalamadoo
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.frontend.deployment.container.port }}

---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: kalamadoo
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.backend.deployment.container.port }}
